version: "3"

services:
  www:
    container_name: Web-Server-Restadvisor
    build: .
    restart: always
    volumes: ["./www:/var/www/html"]
    ports:
      - "8080:80"
    networks:
      - restadvisor
  db-restadvisor:
    container_name: db-restadvisor
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: P4sSw0rd2
      MYSQL_DATABASE: restadvisor
      MYSQL_USER: admin
      MYSQL_PASSWORD: M4sT3r4Dm1n2
    ports:
      - "3306:3306"
    networks:
      - restadvisor
  phpmyadmin:
    depends_on:
      - db-restadvisor
    container_name: phpmyadmin-restadvisor
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db-restadvisor
      MYSQL_ROOT_PASSWORD: P4sSw0rd2
    networks:
      - restadvisor
networks:
  restadvisor:
